name: 'Setup Project'
description: 'Sets up Python, UV, and project dependencies for the th-strava-sensor project'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.13'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      shell: bash
      run: |
        uv sync
